[package]
name = "solana-c-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-sdk = "2.0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"